services:
  - type: web
    name: neon-arcade
    runtime: node
    plan: free
    branch: main
    healthCheckPath: /api/health
    buildCommand: npm install --legacy-peer-deps --legacy-bundling && npm run build
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DATABASE_URL
        value: mongodb+srv://akashchoudhary436_db_user:0dOPuAYtMjBWlEJa@cluster0.luqx4sw.mongodb.net/arcade?retryWrites=true&w=majority
